game_of_life_project/game_of_life/urls.py
from django.urls import path
from game_of_life import views

app_name = 'game_of_life'

urlpatterns = [
     path('', views.index, name='index'),

     path('login/', views.Account.user_login, name='login'),
     path('login_error/', views.Account.user_login_error, name='login_error'),
     path('logout/', views.Account.user_logout, name='logout'),
     path('register/', views.Account.register, name='register'),

     path('game_logic/', views.game_logic, name='game_logic'),
     path('interesting_patterns/', views.interesting_patterns, name='interesting_patterns'),
     path('interesting_patterns/<slug:pattern_name_slug>', views.pattern, name='pattern'),
     path('about/', views.about, name='about'),
     path('all_initial_states/', views.all_initial_states, name='all_initial_states'),

     path('profile/<username>/', views.Profile.profile, name='profile'),
     path('profile/<username>/change_pfp', views.Profile.change_pfp, name='change_pfp'),
     path('profile/<username>/add_friend', views.Profile.add_friend, name='add_friend'),
     path('profile/<username>/remove_friend', views.Profile.remove_friend, name='remove_friend'),
     path('profile/<username>/create_initial_state/', views.Profile.create_initial_state, name='create_initial_state'),
     path('profile/<username>/initial_state/<slug:state_name_slug>', views.Profile.initial_state, name='initial_state'),
     path('profile/<username>/initial_state/<slug:state_name_slug>/saved', views.Profile.save_state, name='save_state'),
     path('profile/<username>/initial_state/<slug:state_name_slug>/unsaved', views.Profile.unsave_state, name='unsave_state'),
     path('profile/<username>/initial_state/<slug:state_name_slug>/liked', views.Profile.like_state, name='like_state'),
     path('profile/<username>/initial_state/<slug:state_name_slug>/unliked', views.Profile.unlike_state, name='unlike_state'),

     path('create_add_pattern/', views.create_add_pattern, name='create_add_pattern'),
    ]

game_of_life_project/game_of_life_project/urls.py
from game_of_life import views
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('game_of_life/', include('game_of_life.urls')),
    # The above maps any URLs starting with game_of_life/ to be handled by game_of_life.
    path('admin/', admin.site.urls)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_of_life_project/game_of_life/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from uuid import uuid4

import os


class InitialState(models.Model):
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    NAME_MAX_LENGTH = 128

    likes = models.IntegerField(default=0)

    state = models.TextField()  # 2d array -> string (JSON)

    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(InitialState, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class InterestingPatten(models.Model):
    state = models.TextField()
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(InterestingPatten, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    moderator = models.BooleanField(default=False)

    # # The additional attributes we wish to include.
  # Images renaming
    def path_and_rename(instance, filename):
        upload_to = 'profile_images'
        ext = filename.split('.')[-1]
        # get filename
        if instance.pk:
            filename = '{}.{}'.format(instance.pk, ext)
        else:
            # set filename as random string
            filename = '{}.{}'.format(uuid4().hex, ext)
        # return the whole path to the file
        return os.path.join(upload_to, filename)

    picture = models.ImageField(blank=True, upload_to=path_and_rename)

    states = models.TextField(blank=True)  # We need a way to store a bunck of states, use json

    def __str__(self):
        return f'{self.user} Profile'



class FriendsList(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    friends = models.ManyToManyField(User, related_name="+")

class LikedAndSaved(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    liked = models.ManyToManyField(InitialState, related_name="+")
    saved = models.ManyToManyField(InitialState, related_name="+")

game_of_life_project/game_of_life/forms.py
from django import forms
from game_of_life.models import UserProfile, InitialState, InterestingPatten
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class InitialStateForm(forms.ModelForm):
    name = forms.CharField(max_length=InitialState.NAME_MAX_LENGTH,
                        help_text="Please enter the states name.")

    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    state = forms.CharField(help_text="or paste in a 2d array manually")
    class Meta:
        model = InitialState
        fields = ('state','name',)

    
class InterestingPatternForm(forms.ModelForm):
    name = forms.CharField(max_length=InterestingPatten.NAME_MAX_LENGTH,
                        help_text="Please enter the states name.")

    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    state = forms.CharField(help_text="or enter state manually.")

    class Meta:
        model = InterestingPatten
        fields = ('state','name',)

game_of_life_project/game_of_life/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views import View


from game_of_life.models import InitialState, UserProfile, InterestingPatten, FriendsList, LikedAndSaved
from game_of_life.forms import UserForm, UserProfileForm, InitialStateForm, InterestingPatternForm

import os



# Home page
def index(request):
    context_dict = {}
    context_dict["most_liked_states"] = InitialState.objects.order_by('-likes')[:6]
    context_dict["most_recent_states"] = InitialState.objects.order_by('-date_created')[:6]
    
    return render(request, 'game_of_life/index.html', context=context_dict)


# Account views
class Account(View):
    def user_login(request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(username=username, password=password)

            if user:
                if user.is_active:
                        login(request, user)
                        return redirect(reverse('game_of_life:index'))
                else:
                        return HttpResponse("Your account is disabled.")
            else:
                print(f"Invalid login details: {username}, {password}")
                return redirect(reverse('game_of_life:login_error'))

        else:
            return render(request, 'game_of_life/login.html')

    def user_login_error(request):
        context_dict = {}

        return render(request, 'game_of_life/login_error.html', context=context_dict)

    @login_required
    def user_logout(request):
        logout(request)
        return redirect(reverse('game_of_life:index'))

    def register(request):
        registered = False

        if request.method == 'POST':
            user_form = UserForm(request.POST)
            profile_form = UserProfileForm(request.POST)

            # If the two forms are valid...
            if user_form.is_valid() and profile_form.is_valid():
                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile = profile_form.save(commit=False)
                profile.user = user

                if 'picture' in request.FILES:
                    profile.picture = request.FILES['picture']

                profile.save()
                registered = True
            else:
                print(user_form.errors, profile_form.errors)
        else:
            user_form = UserForm()
            profile_form = UserProfileForm()

        return render(request,'game_of_life/register.html',
                      context = {'user_form': user_form,
                                 'profile_form': profile_form,
                                 'registered': registered})


# Profile views including states
class Profile(View):
    def profile(request, username):
        context_dict = {}

        try:
            if username == request.user.username:
                context_dict['thisMyPage'] = "true"

            profile_form = UserProfileForm(request.POST)
            context_dict['profile_form'] = profile_form

            user = User.objects.get(username=username)
            states = InitialState.objects.filter(author=user)
            userpic = UserProfile.objects.get(user=user).picture
            context_dict['user'] = user
            context_dict['states'] = states
            context_dict['userpic'] = userpic

            try:
                friends = FriendsList.objects.get(user=user)
                context_dict['friends'] = friends.friends.all()
            except FriendsList.DoesNotExist:
                context_dict['friends'] = ""

            try:
                saved_and_liked_states = LikedAndSaved.objects.get(user=user)
                context_dict['liked_states'] = saved_and_liked_states.liked.all()
                context_dict['saved_states'] = saved_and_liked_states.saved.all()
            except LikedAndSaved.DoesNotExist:
                context_dict['liked_states'] = ""
                context_dict['saved_states'] = ""


            if request.user.is_authenticated:
                try:
                    requester_friends = FriendsList.objects.get(user=request.user)
                    context_dict['requester_friends'] = requester_friends.friends.all()
                except FriendsList.DoesNotExist:
                    context_dict['requester_friends'] = ""


        except User.DoesNotExist:
            context_dict['user'] = None
            context_dict['states'] = None


        return render(request, 'game_of_life/profile.html', context=context_dict)

    def change_pfp(request, username):

        user = User.objects.get(username=username)
        try:
            old_image_path = UserProfile.objects.get(user=user).picture.path
        except: pass #no pic uploaded
        instance = UserProfile.objects.get(user=user)
        form = UserProfileForm(request.POST, request.FILES, instance=instance)

        if form.is_valid():
            try:
                if old_image_path.path.exists(old_image_path):
                    os.remove(old_image_path)
            except: pass

            form.save()
        return redirect('game_of_life:profile', username=username)


    def add_friend(request, username):
        friend = User.objects.get(username=username)
        me = User.objects.get(username=request.user)


        my_friends = FriendsList.objects.get_or_create(user=me)[0]
        my_friends.save()
        my_friends.friends.add(friend)

        friend_friends = FriendsList.objects.get_or_create(user=friend)[0]
        friend_friends.save()
        friend_friends.friends.add(me)

        return redirect('game_of_life:profile', username=username)

    def remove_friend(request, username):
        friend = User.objects.get(username=username)
        me = User.objects.get(username=request.user)


        my_friends = FriendsList.objects.get_or_create(user=me)[0]
        my_friends.save()
        my_friends.friends.remove(friend)

        friend_friends = FriendsList.objects.get_or_create(user=friend)[0]
        friend_friends.save()
        friend_friends.friends.remove(me)

        return redirect('game_of_life:profile', username=username)

    #creation page
    @login_required
    def create_initial_state(request,username):
        context_dict = {}

        form = InitialStateForm()
        if request.method == 'POST':
            form = InitialStateForm(request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.author = request.user
                instance.save()
                return redirect(reverse('game_of_life:index'))
            else:
                print(form.errors)

        context_dict['form'] = form

        user = request.user
        context_dict['user'] = user
        return render(request, 'game_of_life/create_initial_state.html', context=context_dict)

    #completed state page:
    def initial_state(request, username, state_name_slug):
        context_dict = {}
        state = InitialState.objects.get(slug=state_name_slug)
        state.save()
        context_dict["state"] = state
        context_dict["name"] = state.name
        context_dict["author"] = state.author
        context_dict["username"] = username
        context_dict["state_name_slug"] = state_name_slug

        try:
            user = User.objects.get(username=request.user)
            context_dict['user'] = user
            user_liked_and_saved_states = LikedAndSaved.objects.get_or_create(user=user)[0]

            if state in user_liked_and_saved_states.liked.all():
                context_dict["user_already_liked"] = "true"
            else:
                context_dict["user_already_liked"] = None

            if state in user_liked_and_saved_states.saved.all():
                context_dict["user_already_saved"] = "true"
            else:
                context_dict["user_already_saved"] = None

        except User.DoesNotExist:
            context_dict['user'] = None

        return render(request, 'game_of_life/initial_state.html', context=context_dict)

    def like_state(request, username, state_name_slug):
        state = InitialState.objects.get(slug=state_name_slug)

        my_liked = LikedAndSaved.objects.get_or_create(user=request.user)[0]
        my_liked.save()
        my_liked.liked.add(state)

        state.likes += 1
        state.save()

        return redirect('game_of_life:initial_state', username=username, state_name_slug=state_name_slug)

    def unlike_state(request, username, state_name_slug):
        state = InitialState.objects.get(slug=state_name_slug)

        my_liked = LikedAndSaved.objects.get_or_create(user=request.user)[0]
        my_liked.save()
        my_liked.liked.remove(state)

        state.likes-=1
        state.save()

        return redirect('game_of_life:initial_state', username=username, state_name_slug=state_name_slug)

    def save_state(request, username, state_name_slug):
        state = InitialState.objects.get(slug=state_name_slug)

        my_saved = LikedAndSaved.objects.get_or_create(user=request.user)[0]
        my_saved.save()
        my_saved.saved.add(state)


        return redirect('game_of_life:initial_state', username=username, state_name_slug=state_name_slug)




    def unsave_state(request, username, state_name_slug):
        state = InitialState.objects.get(slug=state_name_slug)

        my_saved = LikedAndSaved.objects.get_or_create(user=request.user)[0]
        my_saved.save()
        my_saved.saved.remove(state)





        return redirect('game_of_life:initial_state', username=username, state_name_slug=state_name_slug)


# Moderator page
@login_required

game_of_life_project/templates/game_of_life/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load game_of_life_template_tags %}

<html>
    <head lang="en">
        <link rel="shortcut icon" href="#"> <!-- Bodge relating to error: 404 favicon.ico not found-->
        <meta charset="UTF-8" />
        {% block head_block %}
        {% endblock %}
        <title>
          {% block title_block %}
          {% endblock %}
        </title>
    </head>
    <body>
        <div class="topnav" id="myTopnav">
            <a id="index" href="{% url 'game_of_life:index' %}">Home</a>
            <a id="game_logic" href="{% url 'game_of_life:game_logic' %}">Game Logic</a>
            <a id="interesting_patterns" href="{% url 'game_of_life:interesting_patterns' %}">Interesting patterns</a>
            <a id="about" href="{% url 'game_of_life:about' %}">About</a>
            <a id="all_initial_states" href="{% url 'game_of_life:all_initial_states' %}">All initial states</a>
            <div class="topnav_right">
            {% if request.user.is_authenticated %}
            <a id="profile" href="{% url 'game_of_life:profile' request.user.username %}">My profile</a>
              <a id="create_initial_state" href="{% url 'game_of_life:create_initial_state' request.user.username %}">Create an initial state</a>
              <a id="logout" href="{% url 'game_of_life:logout' %}">Logout</a>
              {% else %} 
              <a id="register" href="{% url 'game_of_life:register' %}">Sign Up</a>
              <a id="login" href="{% url 'game_of_life:login' %}">Login</a>
            {% endif %}
            {% if request.user.is_superuser %}
              <a id="create_add_pattern" href="{% url 'game_of_life:create_add_pattern' %}">Create interesting pattern</a>
            {% endif %}
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
        </div>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <script src="{% static 'js/topnav.js' %}"></script><br />
    </body>
</html>

game_of_life_project/templates/game_of_life/game_logic.html
{% extends 'game_of_life/base.html' %}
{% load staticfiles %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/game_logic.css' %}">
{% endblock %}

{% block title_block %}
    GameLogic page
{% endblock %}

{% block body_block %}

    <div class="game_logic">
    <h1>Game Logic</h1>
    <div class="picture_div">
        <img src="{% static 'images/game.jpg' %}" alt="Picture" class="picture"/>
    </div>
        <p>
        The Game of Life, also known simply as Life, is a cellular automaton devised by 
        the British mathematician John Horton Conway in 1970. It is a zero-player game, 
        meaning that its evolution is determined by its initial state, requiring no further 
        input. One interacts with the Game of Life by creating an initial configuration and 
        observing how it evolves.
    </p>
    <p>
        The universe of the Game of Life is an infinite, two-dimensional orthogonal grid of 
        square cells, each of which is in one of two possible states, live or dead (or 
        populated and unpopulated, respectively). Every cell interacts with its eight 
        neighbours, which are the cells that are horizontally, vertically, or diagonally 
        adjacent. At each step in time, the following transitions occur:
    </p>
    <ol>
        <li>Any live cell with fewer than two live neighbours dies, as if by underpopulation.</li>
        <li>Any live cell with two or three live neighbours lives on to the next generation.</li>
        <li>Any live cell with more than three live neighbours dies, as if by overpopulation.</li>
        <li>Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.</li>
    </ol>
    <p>
        These rules, which compare the behavior of the automaton to real life, can be 
        condensed into the following:
    </p>
    <ol>
        <li>Any live cell with two or three live neighbours survives.</li>
        <li>Any dead cell with three live neighbours becomes a live cell.</li>
        <li>All other live cells die in the next generation. Similarly, all other dead cells stay dead.</li>
    </ol>
    <p>
        If you require further explanation with an example, please consider watching this video:
    </p>
    <iframe class="video" src="https://www.youtube.com/embed/ouipbDkwHWA"
     allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
    </iframe>
    </br>
    {% if user.is_authenticated %}
        <p>
            If you found the game interesting, then follow the 
            <a id="create_initial_state" href="{% url 'game_of_life:create_initial_state' user.username %}">Create an initial state</a> 
                link to try the game out for yourself.
        </p>

    {% else %} 
        <p>
            If you found the game interesting, please log in on the <a id="login" href="{% url 'game_of_life:login' %}">Login</a> page,
            then follow the Create an Initial state link to try the game out for yourself.
        </p>
    {% endif %}
    
    <script>document.getElementById("game_logic").className = "active";</script>
    </div>
{% endblock %}

game_of_life_project/templates/game_of_life/initial_state.html
{% extends 'game_of_life/base.html' %}
{% load staticfiles %}
{% block head_block %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/initial_state.css' %}">

{% endblock %}

{% block title_block %}
    Initial State
{% endblock %}

{% block body_block %}
<div class="initial_state">

    <!-- TITLE -->
    <h1>{{state.name}} by <a href="{% url 'game_of_life:profile' state.author.username %}">{{state.author.username}}</a></h1>

    <!-- PLAYER -->
    <input type="button" value="Return to initial state" id="return" class="button">
    <input type="button" value="Play" id="playback" class="button">
    <label>FPS:</label><input type="range" min="1" max="50" value="20" class="slider" id="fps">

    <canvas id="state">state.state</canvas><br />

    <!-- LIKE AND SAVE -->
    {% if user %}
        {%  if user.username != state.author.username %}
            {% if not user_already_liked %}
                <form action="{% url 'game_of_life:like_state' user.username state_name_slug %}" class="like" onclick="this.disabled=true">
                    <input type="submit" value="Like" class="button" />
                </form>
            {% else %}
                <form action="{% url 'game_of_life:unlike_state' user.username state_name_slug %}" class="like" onclick="this.disabled=true">
                    <input type="submit" value="Unlike" class="button" />
                </form>
            {% endif %}

            {% if not user_already_saved %}
                <form action="{% url 'game_of_life:save_state' user.username state_name_slug %}" onclick="this.disabled=true">
                    <input type="submit" value="Save" class="button" /><br/>
                </form>
            {% else %}
                <form action="{% url 'game_of_life:unsave_state' user.username state_name_slug %}" onclick="this.disabled=true">
                    <input type="submit" value="Unsave" class="button" /><br/>
                </form>
            {% endif %}

        {% endif %}

    {% endif %}
    State name: {{state.name}}, Author:  {{state.author.username}}, Date created: {{state.date_created}}, Likes: {{state.likes}}<br />



    <script type="text/javascript">
        initial_state = JSON.parse('{{state.state}}');
    </script>
    <script src="{% static 'js/view_initial_state.js' %}"></script><br />
    <script>document.getElementById("profile").className = "active";</script>
</div>
{% endblock %}

game_of_life_project/templates/game_of_life/profile.html
{% extends 'game_of_life/base.html' %}
{% load staticfiles %}

{% block head_block %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<link rel="stylesheet" href="{% static 'css/profile.css' %}">

{% endblock %}

{% block title_block %}
    Profile
{% endblock %}

{% block body_block %}

    <div class="profile">

        <!-- TITLE -->
        {% if thisMyPage %}
            <h1 class="profile_heading">My Profile</h1>
        {% else %}
            <h1 class="profile_heading">{{user.username}}'s Profile</h1>
        {% endif %}

        <!-- PROFILE PIC -->
        {% if userpic %}
            <img class="profile_picture" src="{{ userpic.url }}">
        {% else %}
            <img class="profile_picture" src="{% static '/images/default.jpg' %}">
        {% endif %}

        <!-- FRIENDS -->
        <div id="friends">
            {% if thisMyPage %}
                <h4> My friends:</h4>
                {% if friends %}
                    {% for friend in friends %}
                        <a href="{% url 'game_of_life:profile' friend %}">{{friend}}</a>
                    {% endfor %}
                {% endif %}
            {% else %}
                <h4> Their friends:</h4>
                {% if friends %}
                    {% for friend in friends %}
                        <a href="{% url 'game_of_life:profile' friend %}">{{friend}}</a>
                    {% endfor %}
                {% endif %}
                <!-- Add friend !-->
                <p>
                {% if request.user.is_authenticated %}
                    {% if not requester_friends %}
                        <form action="{% url 'game_of_life:add_friend' user.username %}" onclick="this.disabled=true">
                            <input type="submit" value="Friend" class="button"/>
                        </form>
                    {% elif user not in requester_friends %}
                        <form action="{% url 'game_of_life:add_friend' user.username %}" onclick="this.disabled=true">
                            <input type="submit" value="Friend" class="button"/>
                        </form>
                    {% else %}
                        <form action="{% url 'game_of_life:remove_friend' user.username %}" onclick="this.disabled=true">
                            <input type="submit" value="Unfriend" class="button"/>
                        </form>
                    {% endif %}
                {% endif %}

                </p>
            {% endif %}
            </p>


        <!-- CHANGE PFP -->
            {% if thisMyPage %}
            <h4> Change Profile Picture:</h4>
            <form method="POST" enctype="multipart/form-data" action="{% url 'game_of_life:change_pfp' username=request.user.username %}">
                {% csrf_token %}
                {{ profile_form.picture }} <br/>
                <input type="submit" class="button">
            </form>
            {% endif %}
        </div>

        <div id="break"></div>

        <!-- JS FOR STATES -->
        <script>state_list = []</script>

        <!-- USER CREATED STATES -->
        <div>
            {% if thisMyPage %}
                <h2>My states</h2>
            {% else %}
                <h2>Their states</h2>
            {% endif %}

            {% if states %}
                <div class="state_grid">
                {% for state in states %}
                    <div class="state_wrap">
                        <a id="{{state.name}}" href="{% url 'game_of_life:initial_state' user.username state.slug %}"><canvas class="state"></canvas></a>
                        <a class="state_description" href="{% url 'game_of_life:initial_state' user.username state.slug %}">
                            State name: {{state.name}},<br/>
                            Author:  {{state.author.username}},<br />
                            Likes: {{state.likes}}, <br />
                            Date created: {{state.date_created}}
                        </a>
                        <script>state_list.push(JSON.parse('{{state.state}}'))</script>
                    </div>
                {% endfor %}
                </div>
            {% else %}
                User has not made any states
            {% endif %}
        </div>

        <!-- USER LIKED STATES -->
        <div>
            {% if thisMyPage %}
            <h2>My liked states</h2>
            {% else %}
            <h2>Their liked states</h2>
            {% endif %}

            {% if liked_states %}
                <div class="state_grid">
                    {% for state in liked_states %}
                    <div class="state_wrap">
                        <a id="{{state.name}}" href="{% url 'game_of_life:initial_state' state.author state.slug %}"><canvas class="state"></canvas></a>
                        <a class="state_description" href="{% url 'game_of_life:initial_state' state.author state.slug %}">
                            State name: {{state.name}},<br/>
                            Author:  {{state.author.username}},<br />
                            Likes: {{state.likes}}, <br />
                            Date created: {{state.date_created}}
                        </a>
                        <script>state_list.push(JSON.parse('{{state.state}}'))</script>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
            User has not liked any states
            {% endif %}

        </div>

        <!-- USER SAVED STATES -->
        <div>
            {% if thisMyPage %}
            <h2>My saved states</h2>
            {% else %}
            <h2>Their saved states</h2>
            {% endif %}


            {% if saved_states %}
                <div class="state_grid">
                    {% for state in saved_states %}
                    <div class="state_wrap">
                        <a id="{{state.name}}" href="{% url 'game_of_life:initial_state' state.author state.slug %}"><canvas class="state"></canvas></a>
                        <a class="state_description" href="{% url 'game_of_life:initial_state' state.author state.slug %}">
                            State name: {{state.name}},<br/>
                            Author:  {{state.author.username}},<br />
                            Likes: {{state.likes}}, <br />
                            Date created: {{state.date_created}}
                        </a>
                        <script>state_list.push(JSON.parse('{{state.state}}'))</script>
                    </div>
                    {% endfor %}
                </div>
            {% else %}
            User has not saved any states
            {% endif %}

        </div>


        <script src="{% static 'js/initial_state_thumbnails.js' %}"></script>
        <script>document.getElementById("profile").className = "active";</script>

    </div>

{% endblock %}